### ISSUE TITLE
The API example lies!!! (Figure out how to fix it)

### ISSUE THREAD

**Issue by IanDCarroll** [IanDCarroll/impro_bot#1]
__when__ I log on:
`$ npm start`

__then__ I am successfully connected
```
> impro-bot@0.0.1 start /Path/To/MyLocal/impro_bot
> node bot.js

* Connected to irc-ws.chat.twitch.tv:80
```
Responding as myself, `slartibarfastian` (bot logged in as `slartibartfastian` too)
also when any other user is logged in performing the same action against the bot ( bot logged in as `slartibartfastian`)
 - __when__ I message the channel with invalid messages, __then__ the bot successfully gives no response.
 - __when__ it is a valid message to respond to, __then__ things blow up:

```
/Path/To/MyLocal/impro_bot/node_modules/tmi.js/lib/commands.js:377
        return this._sendMessage(this._getPromiseDelay(), channel, message, (resolve, reject) => {
                                      ^

TypeError: this._getPromiseDelay is not a function
    at say (/Path/To/MyLocal/impro_bot/node_modules/tmi.js/lib/commands.js:377:39)
    at respondToGood (/Path/To/MyLocal/impro_bot/lib/tmiAdapter/onMessage.js:7:36)
    at client.respondWithSay (/Path/To/MyLocal/impro_bot/bot.js:16:3)
    at client.EventEmitter.emit (/Path/To/MyLocal/impro_bot/node_modules/tmi.js/lib/events.js:101:25)
    at client.EventEmitter.emits (/Path/To/MyLocal/impro_bot/node_modules/tmi.js/lib/events.js:64:19)
    at client.handleMessage (//Path/To/MyLocal/impro_bot/node_modules/tmi.js/lib/client.js:1003:34)
    at parts.forEach (/Path/To/MyLocal/node_modules/tmi.js/lib/client.js:1080:36)
    at Array.forEach (<anonymous>)
    at client._onMessage (/Path/To/MyLocal/impro_bot/node_modules/tmi.js/lib/client.js:1079:11)
    at WebSocket.onMessage (/Path/To/MyLocal/impro_bot/node_modules/ws/lib/event-target.js:120:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! impro-bot@0.0.1 start: `node bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the impro-bot@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Path/To/.npm/_logs/2020-01-05T00_52_22_610Z-debug.log
```

**Comment by IanDCarroll** [comment]
Learnings: 
 -`tmi.js` is not the api. It's _an_ api for node. 
 - The actual API is accessed though curl requests (pretty sure it's a web socket interface)

What this means:
 - I can debug tmi.js. It's no longer unreasonable to think it can't be broken.
 - I don't need to use node if I don't want to (a lot of work to port the code though)
 - I can figure out how tmi.js is accessing the true api at its base.
 - I can clone tmi.js, make adjustments and then submit a PR if something is actually busted.
 - If it's because of API changes, I can find that out too, but right now, this seems to be an issue with code not calling itself right.

steps:
 1. upgrade node and tmi.js to the latest versions and try again
 2. clone and debug tim.js code - fix it and then submit a PR it's either configuration or a twitch API change
 3. decide if I want to start again and write it in a language of my choosing.
